= Round 2 - The High Seas 

====
All of the answers in this round being with the letter “C”

Possible Points: 10

Time Limit: 15 minutes
====

'''

1.	What does the C stand for in UPC?

2.	The Palme d’Or, or Golden Palm, is the top prize of this annual event and was most recently awarded to Parasite

3.	What car manufacturer can count the Airstream, Cirrus, and PT Cruiser among their discontinued models?

4.	Which island nation sits less than 250 miles from 3 different continents?

5.	What was Queen’s first #1 hit on the Billboard Hot 100 chart?

6.	What unit of measurement, commonly used for firewood, represents 128 cubic feet?

7.	What is the US state capital of the Equality State?

8.	What animal is thought to have evolved most of their unique features in Arctic climates, despite them being commonly found in much warmer climates today?

9.	What TV series picks up 34 years after Daniel LaRusso defeated the title dojo in the All Valley tournament?

10.	Bordering several countries including Kazakhstan and Iran, what is the world’s largest inland body of water?



'''

link:../../../index.html[Click here to return to the main site]