= Disney Boys

[example]
====
All answers are also the name of a male character in a Disney movie.

Possible Points: 10
====

'''

1. What Houston based retailer founded in 2004 sells handbags, accessories and apparel?

2. Also known as the Spruce Goose, this aircraft was intended as a transatlantic flight transport for use during World War II.

3. This versatile grain is packed with vitamins, minerals, and other beneficial plant compounds and is often used in many health food recipes.

4. What name has been commonly used by Indian parents who are considering using a unisex or non-gendered name for their baby?

5. Who lives in the mountains north of Pelican Town and is one of the 12 available bachelors to marry in the game Stardew Valley?

6. What goofy older brother can preteens sympathize with as he learns valuable life lessons on a hit high school sitcom that aired from 1993 to 2000?

7. What do you call a mark left on the skin or within body tissue where a wound, burn, or sore has not healed completely and fibrous connective tissue has developed?

8. This actor was sober at the age of 22 but shocked the world 24 years later with his untimely death in 2014 of a heroin overdose.

9. Considered a leader of the 12 Apostles this person is recognized by the Roman Catholic Church as the very first pope. What is his name?

10.  His trademark is his brutal fighting style and to some he is considered the biggest star of the early 1990s Kung-Fu boom. You might know him by his stage name which is…?

'''

link:../../index.html[Click here to return to the main site]