= Can you hear me now? - Answers

1. "It's gunna be May!" - *"It's gunna be me!" - It's Gunna be Me, NSYNC*
2. "Gotta love these Starbucks lovers." - *"Got a long list of ex lovers." - Blank Space, Taylor Swift*
3. "Hold me closer, Tony Danza." - *"Hold me closer, tiny dancer." - Tiny Dancer, Elton John*
4. "Welcome to the land of flaming sex." - *"Welcome to the land of fame excess" - Party in the USA, Miley Cyrus*
5. "Feel the beat from the tangerine." - *"Feel the beat from the tambourine." - Dancing Queen, ABBA*
6. "We Built This City On Sausage Rolls" - *"We built this city on rock ‘n’ roll" - We Built this City, Starship*
7. "Sweet dreams are made of cheese" - *"Sweet dreams are made of these." - Sweet Dreams, The Eurythmics*
8. "Excuse me while I kiss this guy" - *"Excuse me while I kiss the sky" - Purple Haze, Jimi Hendrix*
9. "It doesn’t make a difference if we’re naked or not" - *"It doesn't make a difference if we make it or not" - Livin' on a Prayer, Bon Jovi*
10. "Then I saw her face, now I’m gonna leave her" - *“Then I saw her face, now I’m a believer” - I’m a Believer, The Monkees*

'''

link:../../../index.html[Click here to return to the main site]