= Quarantine Trivia Week 3
:basepath: questions/round_

=== Your Hosts: Haylie and Mitch

=== Possible Total Points: 125

==== Before we begin, we request that each captain email Haylie with 2 things:
1. Your Team Name
2. Your Vegas Round Choice

The Vegas Round:: 
+
--
Each team may pick one category without an `*` from the list below before starting the game.

For the category you pick, your team gets to choose 5 questions in that round to "bet" on.

If you get a Vegas Round question right, you get 2 points, but if you get it wrong, you get -1 point. 

May the odds be in your favor. When that round comes along make sure your captain marks which questions you are choosing to use for your VR!
--

=== Teams link:teams/april25teams.html[Here]
==== Categories:

1. We Wish You a Merry…
2. Fly That Flag
3. June is Hot, Hot, Hot!*
4. Disney Boys
5. Who’s talking to Who*
6. No one pays attention in History Class
7. Order Matters
8. Short and Sweet
9. Tie Breaker (If necessary)
