= Round 7 Answers - Play Me a Memory 

====
Answers
====

'''

  Based on the vague description of a song, provide the real name of the song and the artist for half a point each

1.	That Teenage Wasteland song
    a.	Real Song Title: *Baba O'Riley*
    b.	Artist: *The Who*
2.	That Pina Colada Song
    a.	Real Song Title: *Escape*
    b.	Artist: *Rupert Holmes*
3.	That Everybody Dance Now song 
    a.	Real Song Title: *Gonna Make You Sweat*
    b.	Artist: *C+C Music Factory*
4.	That song about Ground Control and Major Tom 
    a.	Real Song Title: *Space Oddity*
    b.	Artist: *David Bowie*

  For the following songs, provide the YEAR that they were first released for 1 point each (+/- 2 years)

5.	December 1963 (Oh, What a Night) – The Four Seasons
    a. *1975*
6.	Summer ’68 – Pink Floyd
    a. *1970*
7.	Summer of ’69 – Bryan Adams
    a. *1985*
8.	1985 – Bowling for Soup
    a. *2004*
9.	1999 – Prince
    a. *1982*

  For the final 4 questions, provide the 4 people referred to by NAME in Billy Joel’s song, Piano Man, and their PROFESSION (half a point each, order doesn’t matter)

10.	Person 1
    a.	Name: *John*
    b.	Profession: *Bartender*
11.	Person 2
    a.	Name: *Bill(y)*
    b.	Profession: *Piano Man*
12.	Person 3
    a.	Name: *Paul*
    b.	Profession: *Real Estate Novelist*
13.	Person 4
    a.	Name: *Davy*
    b.	Profession: *Navy*

'''

link:../../../index.html[Click here to return to the main site]