= Couch Potato

[example]
====
How much TV do you actually watch though?

Possible Points: 17

Time Limit: 10 minutes
====

'''

1. Of the 6 main characters, who is the youngest in Friends?

2. In Cheers, Sam Malone used to pitch for what major league baseball team?

3. How many times has Kenny died in the South Park franchise (The entire franchise not just the series, +/- 10)?

4. What does NCIS Stand for?

5. Who was offered the role of Derek Shepard on Gray’s Anatomy (Before Patrick Dempsey) but turned it down?

6. What are the names of Marge's cynical twin sisters in The Simpsons?

7. What are the first names of the four main women in the Sex and the City series?

8. In the first season of the HBO series Game of Thrones, a main character is shockingly beheaded, what is his name and who is the actor that plays him(must have first and last name for character and actor)?

9. The creator of the Dick Van Dyke show just recently passed away, who is he and how old was he when he died?

10. In SpongeBob SquarePants what kind of animal is his pet Gary, and what sound does he make?

'''

link:../../../index.html[Click here to return to the main site]
