= We Wish You a Merry…

==== How well do you know your unofficial holidays?

==== Possible Points: 10

1. In the 1970s, at 4:20pm high school students in California would meet to smoke pot. What is the name of the unofficial holiday celebrated now on April 20th?

2. What holiday originated in 1810 to celebrate the marriage of the crown prince of Bavaria to Princess Therese von Sachsen-Hildburghausen? 

3. What mathematical holiday is celebrated on the day that the month/day format matches the first 3 digits of the constant? 

4. This holiday is celebrated on February 15th as a compliment to Valentine’s day. 

5. Star Wars Day is a full-fledged unofficial holiday, when is it? 

6. What is the unofficial name for the Monday after the Super Bowl? 

7. What holiday created by retailers became popular after its debut in 2005? 

8. What holiday rose to fame after it was invented by Leslie Knope on the TV show Parks and Recreation? 

9. What holiday is based off the secular December celebrations of Frank Costanza? 

10. What holiday do we commemorate the birthday of a soldier often considered the “father of American Calvary”? 
