= To Catch a Thief - Answers

1. WalletHub did a study in 2020 ranking the Safest States in the US. (From their site: _In order to determine the safest states in America, WalletHub compared the 50 states across 53 key safety indicators. Our data set ranges from the state’s coronavirus support to assaults per capita and the unemployment rate._) Using the Overall scores...
    a. Name 3 of the top 10 safest states. *Maine, Vermont, Minnesota, Utah, Wyoming, Iowa, Massachusetts, New Hampshire, Connecticut, Rhode Island*
    b. Name 3 of the worst 10 safest states. *Mississippi, Louisiana, Florida, Arkansas, Texas, Oklahoma, Missouri, Alabama, Georgia, South Carolina*

2. What crime is considered a violent disturbance of the peace by a crowd? *Rioting*

3. According to the FBI, Al Capone quit school after what grade to become a member of a notorious gang? *Sixth Grade*

4. In What years did Alcatraz open and close (+/- 2)? *Opened: August 11, 1934, Closed: March 21, 1963*

5. The highest bail posted in America to date was in 2009, and it was paid. What was the amount (+/- 5 million) and what was the crime? *100,000,000, Insider Trading*


'''

link:../../../index.html[Click here to return to the main site]