= To Catch a Thief

[example]
====
Answer the questions below about safety and crime in America.

Possible Points: 12

Time Limit: 10 minutes
====

'''

1. WalletHub did a study in 2020 ranking the Safest States in the US. (From their site: _In order to determine the safest states in America, WalletHub compared the 50 states across 53 key safety indicators. Our data set ranges from the state’s coronavirus support to assaults per capita and the unemployment rate._) Using the Overall scores...
    a. Name 3 of the top 10 safest states.
    b. Name 3 of the worst 10 safest states.

2. What crime is considered a violent disturbance of the peace by a crowd?

3. According to the FBI, Al Capone quit school after what grade to become a gang member?

4. In what years did Alcatraz open and close (+/- 2)?

5. The highest bail *ever paid* in America to date was in 2009. What was the amount (+/- 5 million) and what was the crime for?


'''

link:../../../index.html[Click here to return to the main site]