= Round 6 - Mystery Round 

====
The answers to the first 9 questions have something in common.
Question 10 is identifying that shared theme.

Possible Points: 12

Time Limit: 15 minutes
====

'''

1.	Known for her many contributions to the field of radioactivity, this chemist was the first woman to win a Nobel Prize

2.	This Marvel superhero wields Mjolnir in his first movie to take on the Frost Giants and his conniving brother

3.	Of the colors of the rainbow, this one has the 2nd-shortest wavelength

4.	Name the only country that is a permanent member of the UN Security Council AND touches the Alps mountain range system

5.	As (the Greek God) Hermes’ Roman equivalent, what god of messages, communication, and more also shares his name with a planet?

6.	As the location of the oldest member of the UC System (and second largest enrollment behind UCLA), what city is home to the Golden Bears campus?

7.	Taking place in the _Alien_ universe, this 2012 Ridley Scott film follows a space crew traveling on the title ship seeking the origins of humanity

8.	Also popular for its export of whiskey, what state did Taylor Swift move to in 2004 to pursue a career in music?

9.	Name the 2018 Syfy series that follows Superman's grandfather on their title homeworld

10.	What do the previous 9 answers have in common (3 points)?

'''

link:../../../index.html[Click here to return to the main site]