= Round 6 Answers - Mystery Round 

====
Answers
====

'''

1.	Known for her many contributions to the field of radioactivity, this chemist was the first woman to win a Nobel Prize
    a. *Marie Curie*

2.	This Marvel superhero wields Mjolnir in his first movie to take on the Frost Giants and his conniving brother
    a. *Thor*

3.	Of the colors of the rainbow, this one has the 2nd-shortest wavelength
    a. *Indigo*

4.	Name the only country that is a permanent member of the UN Security Council AND touches the Alps mountain range system
    a. *France*

5.	As (the Greek God) Hermes’ Roman equivalent, what god of messages, communication, and more also shares his name with a planet?
    a. *Mercury*

6.	As the location of the oldest member of the UC System (and second largest enrollment behind UCLA), what city is home to the Golden Bears campus?
    a. *Berkeley*

7.	Taking place in the _Alien_ universe, this 2012 Ridley Scott film follows a space crew traveling on the title ship seeking the origins of humanity
    a. *Prometheus*

8.	Also popular for its export of whiskey, what state did Taylor Swift move to in 2004 to pursue a career in music?
    a. *Tennessee*

9.	Name the 2018 Syfy series that follows Superman's grandfather on their title homeworld
    a. *Krypton*

10.	What do the previous 9 answers have in common (3 points)?
    a. *They all share names with elements on the periodic table*

'''

link:../../../index.html[Click here to return to the main site]