= Round 2 Answers - The High Seas 

====
Answers
====

'''

1.	What does the C stand for in OPEC?
    a. *Countries* (Organization of the Petroleum Exporting Countries)

2.	The Palme d’Or, or Golden Palm, is the top prize of this annual event and was most recently awarded to _Parasite_
    a. *Cannes Film Festival*

3.	What car manufacturer can count the Airstream, Cirrus, and PT Cruiser among their discontinued models?
    a. *Chrysler*

4.	Which island nation sits less than 250 miles from 3 different continents?
    a. *Cyprus*

5.	What was Queen’s first #1 hit on the Billboard Hot 100 chart?
    a. *Crazy Little Thing Called Love*

6.	What unit of measurement, commonly used for firewood, represents 128 cubic feet?
    a. *Cord*

7.	What is the US state capital of the Equality State?
    a. *Cheyenne*

8.	What animal is thought to have evolved most of their unique features in Arctic climates, despite them being commonly found in much warmer climates today?
    a. *Camel*

9.	What TV series picks up 34 years after Daniel LaRusso defeated the title dojo in the All Valley tournament?
    a. *Cobra Kai*

10.	Bordering several countries including Kazakhstan and Iran, what is the world’s largest inland body of water?
    a. *Caspian Sea*



'''

link:../../../index.html[Click here to return to the main site]