= No one pays attention in History Class

==== Did you know there’s other history than American history?! 

==== Possible Points: 10

1. In just 100 days in 1994, about 800,000 people were slaughtered in Rwanda by what extremist group?

2. The end of what conflict was never marked by a peace treaty rather it died out because the English recognized that the French troops were too strong to be confronted?

3. Vidkun Quisling is one of the most written about people in Norwegian history. What was he notorious for?

4. This group of European communities bonded together to protect their trading interests from the 13th to the 15th century, what were they called?

5. What year did the Irish Famine take place?

6. Who was the architect who rebuilt London after the great fire of 1666?

7. What sport originated in south-eastern England in the 17th century and now has 105 countries playing worldwide?

8. Quisling (after the man in question 3) became synonymous for what English word?

9. Who crowned Napoleon Emperor of France?

10. What nomadic warriors are best known for being ruthless savages and impressive horsemen who terrorized much of Europe in the 4th and 5th centuries A.D.?
