= Round 3 Answers - Love Trapezoid

====
Answers
====

'''

1. Leonardo DiCaprio & Jim Carey
    a. *Kate Winslet* (Titanic & Eternal Sunshine of the Spotless Mind)

2. Jake Gyllenhaal & Julia Stiles
    a. *Heath Ledger* (Brokeback Mountain & 10 Things I Hate About You)

3. Katherine Hepburn & Grace Kelly
    a. *Cary Grant* (Charade & To Catch a Thief)

4. Emma Stone & Rachel McAdams
    a. *Ryan Gosling* (La La Land/Crazy Stupid Love & The Notebook)

5. Christopher Plummer & Dick Van Dyke
    a. *Julie Andrews* (Sound of Music & Mary Poppins)

6. Sandra Bullock & Carrie-Ann Moss
    a. *Keanu Reeves* (The Lake House & The Matrix)

7. Will Farrell & Will Smith
    a. *Eva Mendes* (The Other Guys & Hitch)

8. Kate Hudson & Jennifer Lopez
    a. *Matthew McConaughey* (How to Lose a Guy in 10 Days & The Wedding Planner)

9. Miles Teller & Ansel Elgort
    a. *Shailene Woodley* (The Spectacular Now & The Fault In Our Stars)

10. Jennifer Aniston & Rashida Jones
    a. *Paul Rudd* (Wanderlust & I Love You Man)

'''

link:../../../index.html[Click here to return to the main site]