= Round 5 - Where Have I Heard That? 

====
Provide the original source of the following quotes.  It could be a song, movie, tv show, book, or board game

Possible Points: 12
====

'''

1.	“It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness…”

2.  "Sometimes I'll start a sentence, and I don't even know where it's going. I just hope to find it along the way."

3.	“Shoes on, get up in the morn’, cup of milk, let’s rock and roll, King Kong, kick the drum, rolling on like a Rolling Stone”

4.	“A million dollars isn’t cool. You know what’s cool? A billion dollars.”

5.  "It tastes like feet!"

6.	“There is so much a man can tell you, so much he can say, you remain my power, my pleasure, my pain”

7.	“The game ends when all players have filled in their 13 boxes.”

8.	“Who controls the past controls the future. Who controls the present controls the past.” 

9.	“I live my life a quarter mile at a time.”

10.	“But the years went by and the rock just died, Suzie went and left me for some foreign guy”

11.	“Always move in the direction of the signposts, unless a picture card directs you to move backwards on the path.”

12.	“I am the one who knocks!”


'''

link:../../../index.html[Click here to return to the main site]